_group = {
  {
    group_size = 1,
    pattern = "L",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x1da8,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVSS,VINSERTPS,",
    offsets = "0,0,",
    addresses = "0x1d1d,0x1d3e,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 4,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "VINSERTPS,",
    offsets = "0,",
    addresses = "0x1d29,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVSS,VINSERTPS,",
    offsets = "0,0,",
    addresses = "0x1da2,0x1dc6,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 4,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "VINSERTPS,",
    offsets = "0,",
    addresses = "0x1dcd,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x1d19,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "VINSERTPS,",
    offsets = "0,",
    addresses = "0x1d37,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "VINSERTPS,",
    offsets = "0,",
    addresses = "0x1db8,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x1d23,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 5,
    pattern = "LLSSL",
    opcodes = "VMULPD,VMULPD,VMOVUPD,VMOVUPD,VMULPD,",
    offsets = "32,0,0,32,64,",
    addresses = "0x1d97,0x1d9d,0x1dde,0x1de3,0x1e39,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 160,
    accessed_memory_nooverlap = 96,
    accessed_memory_overlap = 64,
    span = 96,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x1db2,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVSS,VINSERTPS,",
    offsets = "0,0,",
    addresses = "0x1d13,0x1d30,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 4,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "VMULPD,VMOVUPD,",
    offsets = "32,32,",
    addresses = "0x1e33,0x1e49,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 64,
    accessed_memory_nooverlap = 32,
    accessed_memory_overlap = 32,
    span = 32,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVSS,VINSERTPS,",
    offsets = "0,0,",
    addresses = "0x1dac,0x1dbf,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 4,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 13,
    pattern = "SLSLLSSLSLLLL",
    opcodes = "VMOVAPS,VMOVAPS,VMOVAPD,MOV,VMOVAPD,MOV,VMOVAPS,VMOVAPS,VMOVAPD,MOV,VMOVAPD,MOV,CMP,",
    offsets = "-176,-176,-144,-56,-144,-96,-176,-176,-144,-96,-144,-56,-72,",
    addresses = "0x1d59,0x1d66,0x1d6e,0x1d85,0x1d89,0x1df3,0x1dfb,0x1e08,0x1e10,0x1e27,0x1e2b,0x1e4f,0x1e59,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 296,
    accessed_memory_nooverlap = 88,
    accessed_memory_overlap = 208,
    span = 128,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVUPD,",
    offsets = "-64,",
    addresses = "0x1e43,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 32,
    accessed_memory_nooverlap = 32,
    accessed_memory_overlap = 0,
    span = 32,
    head = 0,
    unroll_factor = 1,
  },
}
