_group = {
  {
    group_size = 1,
    pattern = "L",
    opcodes = "CVTSS2SD,",
    offsets = "0,",
    addresses = "0x1580,",
    stride_status = "Success",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "CVTSS2SD,",
    offsets = "0,",
    addresses = "0x1567,",
    stride_status = "Success",
    stride = 8,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
}
